# Generated by Django 2.2.13 on 2021-05-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabissue',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
