# Generated by Django 2.1.7 on 2020-01-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Positive vote'), (0, 'Neutral vote'), (-1, 'Negative vote')], default=0),
        ),
    ]
