# Generated by Django 2.1.7 on 2020-01-29 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20200128_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitlabIssue',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('iid', models.IntegerField()),
                ('state', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], max_length=6)),
                ('labels', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='vote'
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_issues', to='voting.GitlabIssue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_users', to=settings.AUTH_USER_MODEL)),
                ('vote', models.IntegerField(choices=[(1, 'Positive vote'), (0, 'Neutral vote'), (-1, 'Negative vote')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
