# Generated by Django 2.2.9 on 2020-01-29 14:37
from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20200129_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitlabissue',
            old_name='closed_at',
            new_name='gitlab_closed_at',
        ),
        migrations.RenameField(
            model_name='gitlabissue',
            old_name='updated_at',
            new_name='gitlab_updated_at',
        ),
        migrations.AddField(
            model_name='gitlabissue',
            name='gitlab_created_at',
            field=models.DateTimeField(default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gitlabissue',
            name='votes_negative_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gitlabissue',
            name='votes_neutral_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gitlabissue',
            name='votes_positive_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gitlabissue',
            name='votes_total_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gitlabissue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gitlabissue',
            name='iid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Positive vote'), (0, 'Neutral vote'), (-1, 'Negative vote')]),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('issue', 'user'), name='unique_together_issue_user'),
        ),
    ]
