# Generated by Django 2.2.9 on 2020-11-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0001_initial'),
        ('explorations', '0006_auto_20201102_1701')
    ]

    operations = [
        migrations.DeleteModel(
            name='Perimeter',
        ),
    ]
