# Generated by Django 2.1.7 on 2019-04-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='ldap_corresponding_group',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
