# Generated by Django 2.1.7 on 2019-04-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0003_auto_20190408_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='displayname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
