# Generated by Django 2.1.7 on 2019-04-05 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='explorations.Request'),
        ),
        migrations.AlterField(
            model_name='exploration',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explorations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='exploration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='explorations.Exploration'),
        ),
    ]
