# Generated by Django 2.2.9 on 2021-02-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortresult',
            name='create_task_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cohortresult',
            name='request_job_duration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cohortresult',
            name='request_job_fail_msg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datedmeasure',
            name='count_task_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datedmeasure',
            name='request_job_duration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datedmeasure',
            name='request_job_fail_msg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datedmeasure',
            name='request_job_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datedmeasure',
            name='request_job_status',
            field=models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('cancelled', 'cancelled'), ('failed', 'failed'), ('finished', 'finished')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='cohortresult',
            name='request_job_status',
            field=models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('cancelled', 'cancelled'), ('failed', 'failed'), ('finished', 'finished')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='datedmeasure',
            name='fhir_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='datedmeasure',
            name='measure',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cohortresult',
            unique_together=set(),
        ),
    ]
