# Generated by Django 2.1.7 on 2019-10-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
