# Generated by Django 2.1.7 on 2019-04-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorations', '0002_auto_20190405_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='serialized_query',
            field=models.TextField(default='{}'),
        ),
    ]
