# Generated by Django 2.1.7 on 2019-11-05 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explorations', '0003_auto_20191018_1415'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cohort',
            unique_together={('owner', 'fhir_groups_ids', 'type')},
        ),
    ]
