# Generated by Django 2.1.7 on 2019-04-10 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0004_user_displayname'),
        ('explorations', '0003_request_serialized_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cohort.Group'),
        ),
    ]
