# Generated by Django 2.2.13 on 2021-03-16 13:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorations', '0003_auto_20210310_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='perimeters_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None),
        ),
    ]
