# Generated by Django 2.2.13 on 2021-05-04 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explorations', '0004_requestquerysnapshot_perimeters_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_children', to='explorations.Folder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='request',
            name='parent_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='explorations.Folder'),
        ),
        migrations.RunSQL(
            "INSERT INTO explorations_folder(uuid, owner_id, name, created_at, modified_at) "
            "SELECT uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), u.uuid, "
            "'Par défaut', now(), now() "
            "FROM cohort_user u "
            "JOIN explorations_request r "
            "ON r.owner_id=u.uuid "
            "GROUP BY u.uuid "
            "HAVING count(r) > 0;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "UPDATE explorations_request req SET parent_folder_id=uf.folder_uuid "
            "FROM ("
            "SELECT u.uuid owner_uuid, f.uuid folder_uuid "
            "FROM cohort_user u "
            "JOIN ("
            "SELECT DISTINCT ON (owner_id) * FROM explorations_folder WHERE name='Par défaut'"
            ") f ON f.owner_id=u.uuid"
            ") uf WHERE uf.owner_uuid=req.owner_id;",
            reverse_sql=""
        ),
    ]
