# Generated by Django 2.1.7 on 2019-04-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorations', '0004_cohort_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='fhir_patient_id_list',
            field=models.TextField(default=''),
        ),
    ]
