# Generated by Django 2.2.9 on 2020-11-02 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explorations', '0004_auto_20191105_1511'),
    ]

    operations = [
        migrations.RenameModel('Cohort', 'CohortResult'),
        migrations.RenameModel('RequestQueryResult', 'DatedMeasure'),
        migrations.RemoveField(
            model_name='request',
            name='exploration',
        ),
        migrations.DeleteModel(
            name='Exploration',
        ),
    ]
