# Generated by Django 2.2.9 on 2020-11-02 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explorations', '0005_auto_20201102_1539'),
    ]

    operations = [
        #####################
        # ALTER REQUEST
        migrations.AlterField(
            model_name='request',
            name='data_type_of_query',
            field=models.CharField(choices=[('PATIENT', 'FHIR Patient'), ('ENCOUNTER', 'FHIR Encounter')],
                                   default='PATIENT', max_length=9),
        ),

        #####################
        # ALTER REQUEST_QUERY_SNAPSHOT
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='refresh_create_cohort',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='refresh_every_seconds',
            field=models.BigIntegerField(default=0),
        ),

        migrations.AddField(
            model_name='requestquerysnapshot',
            name='is_active_branch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='previous_snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='next_snapshots', to='explorations.RequestQuerySnapshot'),
        ),
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestquerysnapshot',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_snapshots',
                                    to='explorations.Request'),
        ),

        #####################
        # ALTER DATED_MEASURES
        migrations.RenameField(
            model_name='datedmeasure',
            old_name='result_size',
            new_name='measure',
        ),
        migrations.RemoveField(
            model_name='datedmeasure',
            name='perimeter',
        ),
        migrations.AddField(
            model_name='datedmeasure',
            name='fhir_datetime',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),

        #####################
        # ALTER COHORT_RESULT
        migrations.AddField(
            model_name='cohortresult',
            name='dated_measure',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='cohort',
                                    to='explorations.DatedMeasure'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cohortresult',
            name='perimeter',
        ),

        migrations.AddField(
            model_name='cohortresult',
            name='fhir_group_id',
            field=models.CharField(blank=True, default=None, max_length=64),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='cohortresult',
            name='type',
            field=models.CharField(choices=[('IMPORT_I2B2', 'Previous cohorts imported from i2b2.'), (
                'MY_ORGANIZATIONS',
                'Organizations in which I work (care sites with pseudo-anonymised reading rights).'), (
                                                'MY_PATIENTS',
                                                'Patients that passed by all my organizations (care sites with '
                                                'nominative reading rights).'),
                                            ('MY_COHORTS', 'Cohorts I created in Cohort360')], max_length=20),
        ),

        migrations.AddField(
            model_name='cohortresult',
            name='request_job_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cohortresult',
            name='request_job_status',
            field=models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('cancelled', 'cancelled'),
                                            ('finished', 'finished')], default='pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='cohortresult',
            unique_together={('owner', 'fhir_group_id', 'type')},
        ),
    ]
