# Generated by Django 2.2.13 on 2021-05-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorations', '0005_auto_20210504_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='parent_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='explorations.Folder'),
        ),
    ]
