# Generated by Django 2.2.13 on 2021-05-17 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorations', '0006_auto_20210505_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortresult',
            name='request_query_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_results', to='explorations.RequestQuerySnapshot'),
        ),
        migrations.AlterField(
            model_name='datedmeasure',
            name='request_query_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dated_measures', to='explorations.RequestQuerySnapshot'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_folders', to='explorations.Folder'),
        ),
    ]
