# Generated by Django 2.2.13 on 2021-05-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorations', '0007_auto_20210517_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortresult',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='datedmeasure',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
