    # Generated by Django 3.2.5 on 2021-10-20 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorations', '0008_auto_20210519_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortresult',
            name='dated_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort', to='explorations.datedmeasure'),
        ),
        migrations.AlterField(
            model_name='cohortresult',
            name='request_job_status',
            field=models.CharField(choices=[('killed', 'killed'), ('finished', 'finished'), ('running', 'running'), ('started', 'started'), ('error', 'error'), ('unknown', 'unknown'), ('pending', 'pending')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='datedmeasure',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dated_measures', to='explorations.request'),
        ),
        migrations.AlterField(
            model_name='datedmeasure',
            name='request_job_status',
            field=models.CharField(choices=[('killed', 'killed'), ('finished', 'finished'), ('running', 'running'), ('started', 'started'), ('error', 'error'), ('unknown', 'unknown'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
