# Generated by Django 3.2.5 on 2021-11-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorations', '0009_auto_20211020_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortresult',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
